### ISSUE TITLE
There is no code in the project

### ISSUE THREAD

**Issue by dylbrown19** [B4DG3R/TimeSheet#4]
When I try and clone the project there is nothing within the project.

**Comment by B4DG3R** [comment]
I have no idea why this has happened, it may be due to the way I was pushing and merging when I was first learning git.  I have pushed an updated version of the project and then cloned it to check.  All of the data is now in the main repository.

**Comment by B4DG3R** [comment]
Thank you for taking the time to look and raise this issue 👍
